# Using public gist https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
# Latest ubuntu environment available on travis
dist: bionic

language: go

branches:
  only:
  - master
  - dev

# Setup PostgreSQL database.
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

go:
  - 1.16.x

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies.
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

# Make sure you've pinned the version of golangci-lint by running this command
# in your project directory:
#   GO111MODULE=on go get github.com/golangci/golangci-lint@v1.21.0
# You should see this line in your go.mod file:
#   github.com/golangci/golangci-lint v1.21.0
before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  #- go test -v -race ./...  # Run all the tests with the cdrace detector enabled